version: 0.2
phases:
   install:
     runtime-versions:
        java: openjdk8
     commands:
        - apt-get update -y
        - apt-get install -y maven
   build:
    commands:
        - mvn clean install
artifacts:
   files:
      - target/demo-0.0.1-SNAPSHOT.jar
   discard-paths: yes
